### ISSUE TITLE
add scaffolding to this source repository

### ISSUE THREAD

**Issue by KingOfTac** [trans-stat/tas-security#3]
```[tasklist]
### Tasks
- [x] add typescript
- [ ] add rollup
- [x] configure for monorepo using workspaces
- [x] setup build process
- [ ] add unit testing
```

**Comment by KingOfTac** [comment]
I ended up using a lighter bundle/build system using esbuild. This let us trim a ton of dependencies by not using rollup. Adding tests with Cypress is still ongoing. I'm am closing this issue out and will be creating another one specifically for adding tests.
